### ISSUE TITLE
How to tell if it's installed correctly?

### ISSUE THREAD

**Issue by s1u** [kzaher/RegX#2]
After run the project, there is no any sign of that it works or not, no error output in console.app that you mentioned.

Would it be shown or where and what menu its place is under ?

**Comment by kzaher** [comment]
If it's installed correctly, it should created a new item called RegX in submenu of Edit menu item.
![screen shot 2015-01-09 at 18 53 58](https://cloud.githubusercontent.com/assets/1641148/5684460/e51861ba-9830-11e4-8e85-61f7f2ebc557.png)
